### ISSUE TITLE
occur an error

### ISSUE THREAD

**Issue by taasoo** [UmarSpa/HairAnalysis#1]
Thanks your project.
I run the main.py and occur an error:
![error](https://user-images.githubusercontent.com/37069489/36971140-cf8379c4-20a5-11e8-95e9-5bf90374b362.jpg)

**Comment by UmarSpa** [comment]
It used to be just a warning.
Anyhow I have updated the code.
Now it should work without any problem.

**Comment by taasoo** [comment]
Thanks!

**Comment by tinahe75** [comment]
<img width="493" alt="screenshot at jun 12 15-08-40" src="https://user-images.githubusercontent.com/29211639/41324583-1a75a256-6e6a-11e8-84fd-f31abfff8840.png">
Hi, I'm getting a similar error message. The demo always freezes at this stage. 
Thanks in advance!
