### ISSUE TITLE
is this model is classification ?

### ISSUE THREAD

**Issue by nullarch** [UmarSpa/HairAnalysis#2]
i want to segmentation hair from human image in IOS app.
so i tried convert model_caffenet.caffemodel to coreml .
but this model output size is 1000

http://www.eecs.qmul.ac.uk/~urm30/HairMaterial/model_caffenet.caffemodel

**Comment by UmarSpa** [comment]
This is a auxiliary model. In my framework I use the second last layer of this model to extract deep features which are used to perform hair detection, as explained in Section 5.2 of the paper.
