### ISSUE TITLE
Link to download model_caffenet.caffemodel not working

### ISSUE THREAD

**Issue by MonikaAsawa** [UmarSpa/HairAnalysis#3]
Hi,
Instructions says you need to download model_caffenet.caffemodel and place it in Tools/CaffeNet/.
But the link is not working.
I would really appreciate if you could help.
Thanks

**Comment by UmarSpa** [comment]
Hi Monika
I just checked, it is working for me.

**Comment by MonikaAsawa** [comment]
Yes, it is working now.
Thanks & Regards
