### ISSUE TITLE
Thank you and a clarification

### ISSUE THREAD

**Issue by aalavandhaann** [UmarSpa/HairAnalysis#6]
Hello Umar,

Firstly, thank you for the code. I am a student working on 3d reconstruction of hair from single view images. While I am not an expert in machine learning but I have to admit that running your code and getting the results was easy and charm. Yet to run through your code and understanding the paper in parallel is something I am progressing slowly :-). 

I have few questions though, after running your code there are results inside the Output folder. And the results are 
- An image showing the hair region as a binary mask
- An image showing the non-hair region as a binary mark
- An Image showing the hair region probability
- A numpy truth table of shape equal to image size to imply the hair regions in the pixels

Can you tell me how to detect the classification of hair style in the images? Is that part included in the code or is it something to be implemented as another layer? 

Regards,

#0K

**Comment by aalavandhaann** [comment]
Never mind. I was able to solve the problem with a different library. Many thanks for your contribution of this library that led to more learning and understanding. 

Regards,

#0K

**Comment by aayushe** [comment]
> Never mind. I was able to solve the problem with a different library. Many thanks for your contribution of this library that led to more learning and understanding.
> 
> Regards,
> 
> #0K

could you please share how you implemented classification

**Comment by aayushe** [comment]
@aalavandhaann  can you share how you classified the hair types ?

**Comment by aalavandhaann** [comment]
Dear Aayushe,

I did not need to classification of hair types and hence didn't use it. All I needed was only the segmentation of hair region from the rest.
