### ISSUE TITLE
the pretrain_model is not found,

### ISSUE THREAD

**Issue by andrew-begain** [UmarSpa/HairAnalysis#9]

**Comment by tomarraj008** [comment]
http://www.eecs.qmul.ac.uk/~urm30/HairMaterial/model_caffenet.caffemodel.

Not Found
The requested URL /~urm30/HairMaterial/model_caffenet.caffemodel was not found on this server.

**Comment by andrew-begain** [comment]
@tomarraj008 are you face the same qustion? if you has the pretrain_model please tell me,thanks

**Comment by UmarSpa** [comment]
I have just updated the link. It should work now.
Let me know if there is still any problem.

**Comment by tomarraj008** [comment]
Hey Umar  , Thank you for updating the link

**Comment by andrew-begain** [comment]
@UmarSpa thank you very much ,it work now
